---
# Name of the weights file to load
weights_name: best-6.pt
# Directory of model (weights), evaluation results are saved in this directory
experiments_dir: path/to/model/weights
basic:
  # The Cuda device ID, that is needed to enable GPU acceleration during inference
  cuda_device_name: cuda:0
model:
  # The name of the model
  name: resnet_51
dataset:
  # Path to the partition file
  partition_filename: path/to/partition_file
  # Path to the labels' file
  dataset_labels_filename: path/to/dataset_labels_file
  # Path to the file which contains the landmarks information
  landmarks_filename: path/to/landmarks_file
  # Path to the bounding box file
  bounding_boxes_filename: path/to/bounding_boxes_file
  # Path to the folder which contains the images
  dataset_image_folder: path/to/dataset_image_folder
  # Path to the folder which contains the majority class files (baseline guess)
  majority_class_file: path/to/majority_classes_file
  # Path to the testsets
  testsets_path: path/to/evaluation/dataset
evaluation:
  # batch size used during inference (only for speed purpose)
  batch_size: 128
  quantitative:
    # Enable quantitative analysis (0 = disabled, 1 = enabled)
    enabled: 1
  qualitative:
    # Enable qualitative analysis (0 = disabled, 1 = enabled)
    enabled: 1
    # settings for matplotlib plot (choose how many samples are shown)
    number_of_rows: 2
    number_of_images_per_row: 3
    # choose the test set for the random samples
    testset_name: testsetA
